import streamlit as st
import os
from openai import AzureOpenAI

st.set_page_config(page_title="Apex-Orchestrator Core", layout="wide")

# Securely grab production keys from Streamlit secrets or environment variables
# (Addresses Claude's point about production-ready credentials/secrets)
AZURE_ENDPOINT = st.secrets.get("AZURE_OPENAI_ENDPOINT", os.getenv("AZURE_OPENAI_ENDPOINT"))
AZURE_KEY = st.secrets.get("AZURE_OPENAI_KEY", os.getenv("AZURE_OPENAI_KEY"))
DEPLOYMENT_NAME = "gpt-4o" # Your target Azure model deployment

# Initialize the actual enterprise model client
if AZURE_ENDPOINT and AZURE_KEY:
    client = AzureOpenAI(
        azure_endpoint=AZURE_ENDPOINT,
        api_key=AZURE_KEY,
        api_version="2024-02-15-preview"
    )
else:
    st.error("⚠️ Infrastructure Credentials Missing! Running in fallback mode. Please configure Azure Environment Variables.")
    client = None

# --- AGENT DEFINITIONS & PROMPTS (The Core Reasoning Layers) ---
AGENT_01_PROMPT = """
You are the Fabric IQ Study Planner Agent. Your job is to look at a user's target certification goals and current technical level, then generate a highly detailed, personalized, week-by-week study track curriculum.
Be specific with exact technical sub-modules to master.
"""

AGENT_02_PROMPT = """
You are the Work IQ Governance Agent. Your job is to evaluate the study plan generated by Agent 01 against the user's real-world calendar metrics (Meeting Density, Focus Reserve). 
If the calendar shows severe overload (>20 hours of meetings), you must explicitly OVERRIDE Agent 01's plan, scale back the hours, add burnout buffer zones, and issue a structural adjustment notice.
"""

# --- UI WORKSPACE CANVAS ---
st.title("⚙️ Apex-Orchestrator: Live Agent Workspace")

# Inputs mimicking real M365 Graph Signals / Work IQ inputs
with st.sidebar:
    st.header("📊 Live Telemetry Inputs")
    cert_goal = st.text_input("Target Certification", "AZ-400 Designing DevOps Solutions")
    meeting_hours = st.slider("Weekly Meeting Hours (Graph Signal)", 0, 40, 26)
    focus_hours = st.slider("Available Focus Reserve", 0, 40, 6)

if st.button("⚡ Trigger Autonomous Multi-Agent Loop", type="primary"):
    if not client:
        st.warning("Please connect your Azure OpenAI endpoint to execute real-time inference loops.")
    else:
        with st.spinner("Executing agent negotiation & alignment loop..."):
            
            # ──► STEP 1: RUN AGENT 01 (CURRICULUM INGESTION)
            agent1_response = client.chat.completions.create(
                model=DEPLOYMENT_NAME,
                messages=[
                    {"role": "system", "content": AGENT_01_PROMPT},
                    {"role": "user", "content": f"Generate a study path for {cert_goal}. I want to study 12 hours a week."}
                ]
            )
            a1_output = agent1_response.choices[0].message.content
            
            # ──► STEP 2: RUN AGENT 02 (GOVERNANCE EVALUATION & CONFLICT RESOLUTION)
            # We pass Agent 1's work directly into Agent 2 along with the telemetry bounds
            agent2_response = client.chat.completions.create(
                model=DEPLOYMENT_NAME,
                messages=[
                    {"role": "system", "content": AGENT_02_PROMPT},
                    {"role": "user", "content": f"Review this generated plan:\n{a1_output}\n\nCurrent User Telemetry: Meeting Density = {meeting_hours} hours, Focus Reserve = {focus_hours} hours. Determine if an override is mandatory based on your governance constraints."}
                ]
            )
            a2_output = agent2_response.choices[0].message.content
            
            # --- DISPLAY DYNAMIC MULTI-AGENT TRIAL TRACES ---
            col1, col2 = st.columns(2)
            with col1:
                st.markdown("### 🚀 Agent 01 // Fabric IQ Output")
                st.info(a1_output)
                
            with col2:
                st.markdown("### 🛡️ Agent 02 // Work IQ Governance Guard")
                if "OVERRIDE" in a2_output.upper() or meeting_hours > 20:
                    st.error(a2_output)
                else:
                    st.success(a2_output)
