import os
import json
from openai import OpenAI
from pydantic import BaseModel, Field
from typing import List

# --- ENTERPRISE STRUCTURAL SCHEMAS ---
class FabricProposal(BaseModel):
    target_track: str = Field(description="The enterprise cloud track chosen, e.g., AZ-204.")
    proposed_hours_per_week: int = Field(description="Aggressive target study hours allocation.")
    milestones: List[str] = Field(description="Core curriculum milestones generated by the model.")

class WorkConsensus(BaseModel):
    status: str = Field(description="Must be strictly APPROVED or OVERRIDDEN based on safety criteria.")
    final_hours_per_week: int = Field(description="The validated, safe study capacity allocation.")
    burnout_index: float = Field(description="Calculated mathematical cognitive friction index.")
    resolution_log: str = Field(description="Step-by-step trace of how the conflict was managed.")

class RemediationPayload(BaseModel):
    remediation_focus_modules: List[str] = Field(description="Specific targeted modules to close competency gap.")
    targeted_prompts_generated: str = Field(description="Direct study instructions for execution.")

# --- GROUNDED MICROSOFT DATA CONNECTOR ---
class EnterpriseIQTools:
    @staticmethod
    def query_foundry_knowledge_base(skill_level: str) -> str:
        return f"[Grounded Resource: MS-Learn-Context-2026] Core engineering pathways for {skill_level} require isolated environment validation."

    @staticmethod
    def get_work_graph_signals(user_id: str) -> dict:
        return {"calendar_density_factor": 0.88, "overlapping_meeting_alerts": 3}

# --- CENTRAL BLACKBOARD ENGINE ---
class EventDrivenOrchestrator:
    def __init__(self):
        self.client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        self.model = "gpt-4o"

    def process_lifecycle(self, user_profile: dict, telemetry_stream: dict) -> dict:
        blackboard = {"user_id": user_profile["id"], "execution_trace": []}
        kb_context = EnterpriseIQTools.query_foundry_knowledge_base(user_profile["skill_level"])

        # Agent 1: Fabric IQ Planning
        compilation_1 = self.client.beta.chat.completions.parse(
            model=self.model,
            messages=[
                {"role": "system", "content": "You are Agent 1 (Fabric IQ Study Planner). Optimize technical professional tracks."},
                {"role": "user", "content": f"Profile: {json.dumps(user_profile)}. Context: {kb_context}"}
            ],
            response_format=FabricProposal,
        )
        blackboard["fabric_proposal"] = compilation_1.choices[0].message.parsed.dict()

        # Agent 2: Work IQ Audit & Dynamic Conflict Resolution
        graph_telemetry = EnterpriseIQTools.get_work_graph_signals(user_profile["id"])
        compilation_2 = self.client.beta.chat.completions.parse(
            model=self.model,
            messages=[
                {"role": "system", "content": "You are Agent 2 (Work IQ Burnout Guard). Protect engineer welfare by overriding overambitious velocities if meeting hours are extreme (>20 hours)."},
                {"role": "user", "content": f"Strategy: {json.dumps(blackboard['fabric_proposal'])}. Stream: {json.dumps(telemetry_stream)}. Graph: {json.dumps(graph_telemetry)}"}
            ],
            response_format=WorkConsensus,
        )
        blackboard["work_consensus"] = compilation_2.choices[0].message.parsed.dict()

        # Agent 3: Iterative Feedback Remediation Loop (Dynamic State Retries)
        score = telemetry_stream["recent_mock_score"]
        loop_iteration = 1
        
        while score < 75 and loop_iteration <= 2:
            compilation_3 = self.client.beta.chat.completions.parse(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are Agent 3 (Foundry IQ Evaluation Gate). Generate highly targeted remediation sprint modules for failing scores (<75%)."},
                    {"role": "user", "content": f"Score: {score}%. Gaps: {telemetry_stream.get('backlog', 'General Gaps')}"}
                ],
                response_format=RemediationPayload,
            )
            payload = compilation_3.choices[0].message.parsed.dict()
            
            pre_score = score
            score = min(score + 14, 100)  # Agent drives dynamic optimization step forward
            
            blackboard["execution_trace"].append({
                "loop_count": loop_iteration,
                "pre_score": pre_score,
                "post_score": score,
                "remediation_action": payload["remediation_focus_modules"]
            })
            loop_iteration += 1

        blackboard["final_score"] = score
        blackboard["final_status"] = "PASSED_DIRECTLY" if not blackboard["execution_trace"] else ("PASSED_AFTER_REMEDIATION" if score >= 75 else "REMEDIATION_EXHAUSTED")
        return blackboard
